import { expect } from 'jsr:@std/expect'
import { part1, part2 } from "./mod.ts";

const testInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`.split("\n");

Deno.test(function solutionPart1Test() {
  expect(part1(testInput)).toBe(21);
});

Deno.test(function solutionPart2Test() {
  expect(part2(testInput)).toBe(40);
});